config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :adverts, only: [:index, :show]

  authenticate :user, ->(u) { u.admin? } do
    namespace :admin do
      resources :adverts, only: %i[index]
    end
  end

  authenticate :user, ->(u) { u.client? } do
    namespace :client do
      resources :adverts, only: %i[index show]
    end
  end


  namespace :api do
    namespace :v1 do
      resources :adverts, only: %i[create update index show]
    end
  end
end

app/models/advert.rb
class Advert < ApplicationRecord
  include AASM
  aasm do
    state :publicated, initial: true
    state :sold

    event :sell do
      transitions from: :publicated, to: :sold
    end
  end

  has_many :requests

  belongs_to :user
  belongs_to :category

  validates_length_of :article, :is => 5
  validates :title, presence: true

end

app/models/advert/foto.rb
class Advert::Foto < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :adverts
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :advert

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name,
    presence: true,
    length: {maximum: 50},
    on: :create

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :adverts

  def client?
    !admin?
  end
end

app/controllers/admin/adverts_controller.rb
class Admin::AdvertsController < ApplicationController
  def index
    @adverts = Advert.all
  end

end

app/controllers/adverts_controller.rb
class AdvertsController < ApplicationController
  def index
    render json: Advert.all
  end

  def show
    advert = Advert.find_by(id: params[:id])
    if advert
      render json: advert
    else
      head 404
    end
  end

  def create
    advert = Advert.new(advert_params)
    advert.save!
  end

  private

  def advert_params
    params.require(:advert).permit(:title, :article, :user_id)
  end
end

app/controllers/api/v1/adverts_controller.rb
class Api::V1::AdvertsController < ApplicationController
  def index
   adverts =  Advert.all
   render json: adverts
  end

  def show
    advert = Advert.find_by(id: params[:id])
    if advert
      render json: advert
    else
      head 404
    end
  end

  def create
    advert = Advert.new(advert_params)
    advert.save!
  end

  def update
    advert = Advert.find(params[:id])
    advert.update(advert_params)
  end

  private

  def advert_params
    params.require(:advert).permit(:title, :article, :user_id, :category_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    if resource.admin?
      admin_adverts_path
    else
      client_adverts_path
    end
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end

  protected

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}

      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
  end

end

app/controllers/client/adverts_controller.rb
class Client::AdvertsController < Client::BaseController
  def index
    @adverts = current_user.adverts
  end

  def show
    @advert = Advert.find_by(id: params[:id])
  end
end

app/controllers/client/base_controller.rb
class Client::BaseController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/adverts/index.erb
<h1>Hello <%= current_user.name %></h1>
<h2>You are admin</h2>

<% if @adverts.any? %>
  <h4>All adverts</h4>
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Content</th>
        <th>Author of advert</th>
      </tr>
    </thead>

    <tbody>
      <% @adverts.each do |advert| %>
        <tr>
          <td><%= advert.article %></td>
          <td><%= advert.title %></td>
          <td><%= advert.user.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h4>List is empty</h4>
<% end %>

<br>

app/views/client/adverts/index.erb
<h1>Hello <%= current_user.name %></h1>
<h2>You are client</h2>

<% if @adverts.any? %>
  <h4>Your list of adverts</h4>
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Content</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @adverts.each do |advert| %>
        <tr>
          <td><%= link_to advert.article, client_advert_path(advert)  %></td>
          <td><%= advert.title %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h4>Your list of adverts is empty</h4>
<% end %>

<br>

app/views/client/adverts/show.erb
<h2>Advert</h2>
<h3>Article is "<%= @advert.article %>"</h3>
<h3>Title is "<%= @advert.title %>"</h3>

<h4>List of users requested for your adverts</h4>

  <body>
    <% @advert.requests.each do |request| %>
    <table>
      <tr>
        <td>Name - <%=request.user.name %></td>
      </tr>
      <tr>
        <td>Email - <%=request.user.email %></td>
      </tr>
      <tr>
        <td>Request title - <%=request.title %></td>
      </tr>
      <tr>
        <td>Bid price - <%=request.bid_price %></td>
      </tr>
    <table>
    <%end%>
  </body>

<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Buyservice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <p class="navbar-text float-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    </p>
    <% if current_user %>
      <% if current_user.admin? %>
        <%= link_to 'Home page', admin_adverts_path %>
      <% elsif current_user.client?%>
          <%= link_to 'Home page', client_adverts_path %>
      <% end %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <% end %>

    <%= yield %>
  </body>


</html>